
function toNum(v){return Number(v||0);}
let lang='en';
const L = { en:{ title:'Melting Pro 2.0 - Aarav Steel Tech', subtitle:'Offline furnace calculators', select:'Select Calculator', opt1:'Si-Mn Required (target Mn%)', opt2:'Mn Recovery (%)', opt3:'Carbon Down (by sponge FeO)', opt4:'FeO from Fe(M)', calc:'Calculate', reset:'Reset' }, hi:{ title:'Melting Pro 2.0 - आरव स्टील टेक', subtitle:'ऑफ़लाइन फर्नेस कैलकुलेटर', select:'कैलकुलेटर चुनें', opt1:'Si-Mn आवश्यक (लक्षित Mn%)', opt2:'Mn रीकवरी (%)', opt3:'कार्बन घटाना (sponge FeO से)', opt4:'Fe(M) से FeO निकालो', calc:'गणना करें', reset:'रीसेट' } };
function t(k){ return L[lang][k] || k; }
function renderTexts(){ document.getElementById('title').textContent = t('title'); document.getElementById('subtitle').textContent = t('subtitle'); document.getElementById('selLabel').textContent = t('select'); document.getElementById('opt1').textContent = t('opt1'); document.getElementById('opt2').textContent = t('opt2'); document.getElementById('opt3').textContent = t('opt3'); document.getElementById('opt4').textContent = t('opt4'); document.getElementById('calcBtn').textContent = t('calc'); document.getElementById('resetBtn').textContent = t('reset'); document.getElementById('langBtn').textContent = (lang==='en') ? 'हिंदी' : 'EN'; }
function init(){ document.getElementById('langBtn').addEventListener('click', ()=>{ lang = (lang==='en') ? 'hi' : 'en'; renderTexts(); }); document.getElementById('calcBtn').addEventListener('click', doCalc); document.getElementById('resetBtn').addEventListener('click', resetAll); document.getElementById('calculator').addEventListener('change', switchUI); renderTexts(); switchUI(); if('serviceWorker' in navigator){ navigator.serviceWorker.register('service-worker.js').catch(()=>{}); } }
function switchUI(){ const v = document.getElementById('calculator').value; document.querySelectorAll('.calc-section').forEach(s=>s.style.display='none'); if(v==='1') document.getElementById('sec1').style.display='block'; if(v==='2') document.getElementById('sec2').style.display='block'; if(v==='3') document.getElementById('sec3').style.display='block'; if(v==='4') document.getElementById('sec4').style.display='block'; document.getElementById('allRes').textContent=''; }
/* calculators */
function calcSiMnRequired(){ const heat = toNum(document.getElementById('heatKg').value); const cur = toNum(document.getElementById('curMn').value); const target = toNum(document.getElementById('targetMn').value); const alloy = toNum(document.getElementById('alloyMn').value); const rec = toNum(document.getElementById('recMn').value); if(alloy<=0 || rec<=0){ return 'Alloy Mn% and Recovery% must be >0'; } const x = (target - cur) * heat * 100.0 / (alloy * rec); return {kg:x}; }
function calcMnRecovery(){ const metal = toNum(document.getElementById('rec_metalKg').value); const mnMetal = toNum(document.getElementById('rec_mnMetal').value); const alloyW = toNum(document.getElementById('rec_alloyKg').value); const mnAlloy = toNum(document.getElementById('rec_mnAlloy').value); if(alloyW<=0 || mnAlloy<=0) return 'Alloy weight and Mn% in alloy must be >0'; const recovery = (metal * (mnMetal/100.0)) / (alloyW * (mnAlloy/100.0)) * 100.0; return {recovery: recovery}; }
function calcCarbonByFeO(){ const metalKg = toNum(document.getElementById('c_metalKg').value); const drop = toNum(document.getElementById('c_drop').value); const feo = toNum(document.getElementById('c_feo').value); if(feo<=0) return 'FeO% must be >0'; const metalTon = metalKg/1000.0; const spongeKg = (drop * metalTon) / (0.1 * feo); return {spongeKg: spongeKg}; }
function calcFeOfromFeM(){ const fetot = toNum(document.getElementById('fe_tot').value); const fem = toNum(document.getElementById('fe_m').value); if(fetot <= fem) return 'Fe total must be greater than Fe(M)'; const feo = (fetot - fem) / 0.777; return {feo: feo}; }
function doCalc(){ const sel = document.getElementById('calculator').value; let res; if(sel==='1') res = calcSiMnRequired(); if(sel==='2') res = calcMnRecovery(); if(sel==='3') res = calcCarbonByFeO(); if(sel==='4') res = calcFeOfromFeM(); const out = document.getElementById('allRes'); if(typeof res === 'string'){ out.textContent = res; return; } if(res.kg !== undefined) out.innerHTML = 'Add ' + res.kg.toFixed(2) + ' kg of Si-Mn (approx)'; else if(res.recovery !== undefined) out.innerHTML = 'Mn Recovery ≈ ' + res.recovery.toFixed(2) + ' %'; else if(res.spongeKg !== undefined) out.innerHTML = 'Add ' + res.spongeKg.toFixed(1) + ' kg sponge (approx)'; else if(res.feo !== undefined) out.innerHTML = 'Estimated FeO in sponge ≈ ' + res.feo.toFixed(2) + ' %'; else out.textContent = JSON.stringify(res); }
function resetAll(){ document.querySelectorAll('input').forEach(i=>i.value=''); document.getElementById('allRes').textContent=''; }
document.addEventListener('DOMContentLoaded', init);
