
const texts={en:{feoTitle:"FeO → Metallic Fe",siTitle:"Si & Mn Recovery",slagTitle:"Slag Basicity",carbonTitle:"Carbon % Change",calc:"Calculate",reset:"Reset",addHome:"Add to Home Screen"},hi:{feoTitle:"FeO → धात्विक Fe",siTitle:"Si और Mn रिकवरी",slagTitle:"स्लीग बेसिसिटी",carbonTitle:"कार्बन % परिवर्तन",calc:"गणना करें",reset:"रीसेट",addHome:"होम स्क्रीन पर जोड़ें"}};
let lang='en';
function initUI(){document.getElementById('langBtn').addEventListener('click',()=>{lang=(lang==='en')?'hi':'en';renderTexts();});document.getElementById('calcFeo').addEventListener('click',calcFeo);document.getElementById('calcSiMn').addEventListener('click',calcSiMn);document.getElementById('calcSlag').addEventListener('click',calcSlag);document.getElementById('calcCarbon').addEventListener('click',calcCarbon);document.getElementById('resetAll').addEventListener('click',resetAll);document.getElementById('addHome').addEventListener('click',()=>{alert(lang==='en'?'Open Chrome menu → Add to Home screen':'Chrome मेन्यू खोलकर → Add to Home screen');});renderTexts();}
function renderTexts(){document.getElementById('title').textContent='Melting Pro 2.0';document.getElementById('subtitle').textContent=(lang==='en')?'Induction furnace tools — English / Hindi':'इंडक्शन फ़रनेस टूल्स — अंग्रेज़ी / हिंदी';document.getElementById('feoTitle').textContent=(lang==='en')?texts.en.feoTitle:texts.hi.feoTitle;document.getElementById('siTitle').textContent=(lang==='en')?texts.en.siTitle:texts.hi.siTitle;document.getElementById('slagTitle').textContent=(lang==='en')?texts.en.slagTitle:texts.hi.slagTitle;document.getElementById('carbonTitle').textContent=(lang==='en')?texts.en.carbonTitle:texts.hi.carbonTitle;document.getElementById('calcFeo').textContent=(lang==='en')?texts.en.calc:texts.hi.calc;document.getElementById('calcSiMn').textContent=(lang==='en')?texts.en.calc:texts.hi.calc;document.getElementById('calcSlag').textContent=(lang==='en')?texts.en.calc:texts.hi.calc;document.getElementById('calcCarbon').textContent=(lang==='en')?texts.en.calc:texts.hi.calc;document.getElementById('resetAll').textContent=(lang==='en')?texts.en.reset:texts.hi.reset;document.getElementById('addHome').textContent=(lang==='en')?texts.en.addHome:texts.hi.addHome;document.getElementById('langBtn').textContent=(lang==='en')?'हिंदी':'EN';}
function calcFeo(){const feo=parseFloat(document.getElementById('feoPct').value)||0;const metallic=Math.max(0,100-feo*0.43);document.getElementById('feoRes').textContent=metallic.toFixed(3)+' %';}
function calcSiMn(){const metalWt=parseFloat(document.getElementById('metalWt').value)||0;const siMetalPct=parseFloat(document.getElementById('siMetalPct').value)||0;const mnMetalPct=parseFloat(document.getElementById('mnMetalPct').value)||0;const alloyWt=parseFloat(document.getElementById('alloyWt').value)||0;const siAlloyPct=parseFloat(document.getElementById('siAlloyPct').value)||0;const mnAlloyPct=parseFloat(document.getElementById('mnAlloyPct').value)||0;const siInMetal=(siMetalPct/100.0)*metalWt;const mnInMetal=(mnMetalPct/100.0)*metalWt;const siCharged=(siAlloyPct/100.0)*alloyWt;const mnCharged=(mnAlloyPct/100.0)*alloyWt;const siRecovery=siCharged>0?(siInMetal/siCharged)*100:0;const mnRecovery=mnCharged>0?(mnInMetal/mnCharged)*100:0;document.getElementById('siRes').textContent=siRecovery.toFixed(2)+' %';document.getElementById('mnRes').textContent=mnRecovery.toFixed(2)+' %';}
function calcSlag(){const cao=parseFloat(document.getElementById('cao').value)||0;const mgo=parseFloat(document.getElementById('mgo').value)||0;const sio2=parseFloat(document.getElementById('sio2').value)||0;const al2o3=parseFloat(document.getElementById('al2o3').value)||0;const denom=sio2+al2o3;const basicity=denom>0?(cao+mgo)/denom:0;document.getElementById('slagRes').textContent=basicity.toFixed(3);}
function calcCarbon(){const cBath=parseFloat(document.getElementById('cBath').value)||0;const wBath=parseFloat(document.getElementById('wBath').value)||0;const cAdd=parseFloat(document.getElementById('cAdd').value)||0;const wAdd=parseFloat(document.getElementById('wAdd').value)||0;const finalC=((cBath/100)*wBath+(cAdd/100)*wAdd)/Math.max(1e-9,(wBath+wAdd));document.getElementById('carbonRes').textContent=(finalC*100).toFixed(3)+' %';}
function resetAll(){document.querySelectorAll('input').forEach(i=>i.value='');document.getElementById('feoRes').textContent='';document.getElementById('siRes').textContent='';document.getElementById('mnRes').textContent='';document.getElementById('slagRes').textContent='';document.getElementById('carbonRes').textContent='';}
document.addEventListener('DOMContentLoaded',()=>{initUI();if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}});
